pasta = ("Pasta Arrabiata" , "Italian" , 20 , "Medium")
biryani = ("Chicken biryani" , "Indian " , 45 , "Hard")
print("================")
print("Recipe 1:" , pasta)
print("Name:" , pasta[0])
print("Cuisine:" , pasta[1])
print("Difficulty :" , pasta[-1])
print("================")
all_recipes = (pasta , biryani)
print("/nFirst recipe name :" , all_recipes[0][0])
print("Second recipe time :" , all_recipes[1][2])
print("Pasta details (sliced) :" , pasta[1 : 3])
print("/nPasta Recipe details :")
print("================")
for detail in pasta:
    print(" -" , detail)
pasta_ingredents = {"tomato" , "garlic" , "olive oil" , "chilli" , "pasta" , "garlic"}
biryani_ingredents = {"rice" , "chicken" , "garlic" , "onion" , "tomato" , "spices"}
print("================")
print("/nPasta ingredents :" , pasta_ingredents)
print("Biryani ingredents :" , biryani_ingredents)
print("Total pasta ingredents :" , len(pasta_ingredents))
print("================")
pasta_ingredents.add("parmesan")
pasta_ingredents.discard("chilli")
all_ingredents = pasta_ingredents.union(biryani_ingredents)
common =  pasta_ingredents.intersection(biryani_ingredents)
only_pasta =  pasta_ingredents.difference(biryani_ingredents)
unique_to_each =  pasta_ingredents.symmetric_difference(biryani_ingredents)
print("================")
print("All ingedents :" , all_ingredents)
print("common ingedents :" , common)
print("================")
print("Only pasta ingredents :" , only_pasta)
print("Unique ingredents :" , unique_to_each)